### ISSUE TITLE
error attempt to index a nil value local esx

### ISSUE THREAD

**Issue by ShoeLace1291** [jonassvensson4/jsfour-atm#10]
Error loading script server.lua in resource jsfour-atm: @jsfour-atm/server.lua:12: attempt to index a nil value (local 'ESX')
stack traceback:
@jsfour-atm/server.lua:12: in main chunk
Failed to load script server.lua.
Started resource jsfour-atm

Any idea how to fix this?

**Comment by jonassvensson4** [comment]
`attempt to index a nil value (local 'ESX')` means it can't find ESX. 

I assume you have it installed which means you have messed up your start order.
