### ISSUE TITLE
 I click "e" and nothing happens.

### ISSUE THREAD

**Issue by wujekhejter** [jonassvensson4/jsfour-atm#11]
My work:

I go to the bank or ATM and after pressing “E” Nothing happens. Has anyone already had this “problem”?
I sit for a few hours and wonder what I’m doing wrong.
What I did:

I turned off the server.cfg
New-banking, esx-atm and deleted them from ftp.
I have added the start of jsfour-atm
I added a table to the database.
There is no error.
I think I need a bank to interact with this plugin?
The question is whether I am right and what. I do not have an idea anymore.

I’m using a google translator. I hope that it is clearly written :frowning:

**Comment by jonassvensson4** [comment]
1. Do you get a notificaiton that's telling you to press E to open it?
2. Have you checked both the server console AND the client console for errors?

**Comment by wujekhejter** [comment]
Hey! I'll probably give you as much information as I can.
Yes, I have a message press "E"

1. The console in hosting, as yet not connect to the server
- Error loading script server.lua in resource jsfour-atm: server.lua: 12: attempt to index a nil value (local 'ESX')

2. After teleporting to / tp 89.75 2.35 68.31
Pressing "E" crashes the error in the console on the hosting
- es_extended: TriggerServerCallback => [jsfour-atm: getMoney] does not exist

3. I am not able to give much information from the game console "F8" because it scrolls every now and then I can not deal with it.
Is there any convenient script that can check the client's errors from the computer's level?

I have two servers and this one is for testing because if you have any idea what can be not so bold give what to change, because I do not care about this server. <-- test server

I have a live server on which I can transfer files that are 100% functional.

**Comment by jonassvensson4** [comment]
Okay so first you're telling me you didn't get any errors and now you're showing me 3 different errors.

`Error loading script server.lua in resource jsfour-atm: server.lua: 12: attempt to index a nil value (local 'ESX')`
`es_extended: TriggerServerCallback => [jsfour-atm: getMoney]`

This means you've messed up your resource start order. My script uses functions from es_extended which means it can't be started before that script.

Please take a look at the start order recommended by ESX themselves 
https://esx-org.github.io/faq/

**Comment by wujekhejter** [comment]
Thank you for your help. it works. I have other smaller problems, but somehow solve them <3
