### ISSUE TITLE
eventcall back NEEDED when u press escape or move away from mb

### ISSUE THREAD

**Issue by jpedror1005** [jonassvensson4/jsfour-atm#14]
when you press escape before take out money to close menu without withdraw money it causes the freezes that players are messing with.. they got there to check the beauty of the system and .. baiiit....
 i think something its needed  for the players to use escape before take money from ATM.

there is on client.lua

130> Close the NUI/HTML window
131> RegisterNUICallback('escape', function(data, cb)
132> 	SetNuiFocus(false, false)
133> 	open = false
134> 	cb('ok')

but for some reason before taking out the money people freezes on trying to leave atm! i love your script and i would want to throw it away  :(

**Comment by jonassvensson4** [comment]
You can press escape whenever you want and it won't freeze the player. If the player gets stuck when pressing escape it means that the folder got the wrong name. It can't have any other name than **jsfour-atm**. Nothing else will work. 

I have no idea what you mean with "move away from mb".
