### ISSUE TITLE
Error when using bank

### ISSUE THREAD

**Issue by JuannmaCh** [jonassvensson4/jsfour-atm#27]
Hello! I get this when I use the bank such as Fleeca from Legion Square (not atm):

![image](https://user-images.githubusercontent.com/49504419/79030677-908dff00-7b70-11ea-83c7-6a8e01542f19.png)

Am I missing something? How can I fix it? Thanks a lot

**Comment by jnsvns** [comment]
Use it how? Do you get that error by just opening it? What value is null?
