### ISSUE TITLE
deposit full amount instead of amount selected

### ISSUE THREAD

**Issue by rahafuf** [jonassvensson4/jsfour-atm#30]
four some reason when I go to deposit money it deposits it all instead of the amount I have selected. is there a way to fix that? is there a way to fix this???

**Comment by jnsvns** [comment]
The default version of the resource doesn't deposit all of your money unless you press the button where it says "all". So I'm not sure how I'm supposed to help you. You'll have to debug it yourself.

Create an pull request if you find any issues in the code.

**Comment by rahafuf** [comment]
what i used is the default version. the one that you have linked here. clicking any number deposits everything.

**Comment by jnsvns** [comment]
I've just tried it and it doesn't deposit everything for me. Which makes it extremely difficult for me to help you.
