### ISSUE TITLE
Probably a bug in  the Bank menu

### ISSUE THREAD

**Issue by Evolyck** [jonassvensson4/jsfour-atm#8]
Hello, i  installed the resource fine and the atm is working just fine the problem is:
I can't  do deposits,withdraw or transfer money   with the bank menu,  i only can deposit or withdraw on a ATM.

Can you help me  please?

**Comment by jonassvensson4** [comment]
I just downloaded the GitHub version and it works fine for me. And 107 servers are using it so I guess it should be working fine.

Are you sure you're pressing the button twice? You need to press the button once to get to the page and then fill in your amount and press the button once again

**Comment by Evolyck** [comment]
Nevermind, i fucked up while doing the translation to portuguese because i own a  Pt rp server.
Btw is it normal the .sql not having a primary key? if not where i should add it?

**Comment by jonassvensson4** [comment]
I'm closing this since you said it's the translation that fucked it up. If you have questions or find a bug please create a new issue or add me on discord jonassvensson4#3011
