### ISSUE TITLE
need help to make it compatible with esx_kashacters

### ISSUE THREAD

**Issue by XxFri3ndlyxX** [jonassvensson4/jsfour-atm#9]
at first i could not use the atm but i fixed it by adding if xplayer ~= nil  "your codecode" end
but then i got this error 
`Error running system event handling function for resource jsfour-atm: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server.lua:136: attempt to index a nil value
stack traceback:
        server.lua:136: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>`

I am not sure how to fix this. Could someone help me with that? Thanks!

**Comment by jonassvensson4** [comment]
You get an error at server.lua:136. 

I can't find any index value on that line so you must have modified the file.
